import { defineConfig } from "oxlint"

export default defineConfig({
  plugins: ["unicorn", "typescript", "oxc"],
  ignorePatterns: [
    "**/dist",
    "**/build",
    "**/docs",
    "**/*.md",
    "**/*.cjs",
    "**/*.js",
    "node_modules",
    ".output",
    ".worktrees/",
  ],
  settings: {
    "jsx-a11y": {
      polymorphicPropName: null,
      components: {},
      attributes: {},
    },
    next: {
      rootDir: [],
    },
    react: {
      formComponents: [],
      linkComponents: [],
      version: null,
      componentWrapperFunctions: [],
    },
    jsdoc: {
      ignorePrivate: false,
      ignoreInternal: false,
      ignoreReplacesDocs: true,
      overrideReplacesDocs: true,
      augmentsExtendsReplacesDocs: false,
      implementsReplacesDocs: false,
      exemptDestructuredRootsFromChecks: false,
      tagNamePreference: {},
    },
    vitest: {
      typecheck: false,
    },
  },
  env: {
    builtin: true,
  },
  jsPlugins: [
    "@effect/eslint-plugin",
    { name: "jsdoc-js", specifier: "eslint-plugin-jsdoc" },
    { name: "local", specifier: "./oxlint-local-plugin.cjs" },
    { name: "local-advanced", specifier: "./oxlint-local-advanced-plugin.cjs" },
  ],
  rules: {
    "constructor-super": "deny",
    curly: "deny",
    "for-direction": "deny",
    "getter-return": "deny",
    "no-array-constructor": "deny",
    "no-async-promise-executor": "deny",
    "no-case-declarations": "deny",
    "no-class-assign": "deny",
    "no-compare-neg-zero": "deny",
    "no-cond-assign": "deny",
    "no-console": "allow",
    "no-const-assign": "deny",
    "no-constant-binary-expression": "deny",
    "no-constant-condition": "deny",
    "no-control-regex": "deny",
    "no-debugger": "deny",
    "no-delete-var": "deny",
    "no-undef": "allow",
    "no-dupe-class-members": "deny",
    "no-dupe-else-if": "deny",
    "no-dupe-keys": "deny",
    "no-duplicate-case": "deny",
    "no-empty": "deny",
    "no-empty-character-class": "deny",
    "no-empty-pattern": "deny",
    "no-empty-static-block": "deny",
    "no-ex-assign": "deny",
    "no-extra-boolean-cast": "deny",
    "no-fallthrough": "deny",
    "no-func-assign": "deny",
    "no-global-assign": "deny",
    "no-import-assign": "deny",
    "no-invalid-regexp": "deny",
    "no-irregular-whitespace": "deny",
    "no-loss-of-precision": "deny",
    "no-misleading-character-class": "deny",
    "no-new-native-nonconstructor": "deny",
    "no-nonoctal-decimal-escape": "deny",
    "no-obj-calls": "deny",
    "no-prototype-builtins": "deny",
    "no-redeclare": "deny",
    "no-regex-spaces": "deny",
    "no-self-assign": "deny",
    "no-setter-return": "deny",
    "no-shadow-restricted-names": "deny",
    "no-sparse-arrays": "deny",
    "no-this-before-super": "deny",
    "no-unexpected-multiline": "deny",
    "no-unreachable": "deny",
    "no-unsafe-finally": "deny",
    "no-unsafe-negation": "deny",
    "no-unsafe-optional-chaining": "deny",
    "no-unused-expressions": "deny",
    "no-unused-labels": "deny",
    "no-unused-private-class-members": "deny",
    "no-useless-backreference": "deny",
    "no-useless-catch": "deny",
    "no-useless-escape": "deny",
    "no-useless-rename": "deny",
    "no-var": "deny",
    "no-warning-comments": "deny",
    "no-with": "deny",
    "prefer-const": "deny",
    "require-yield": "deny",
    "use-isnan": "deny",
    "valid-typeof": "deny",
    "import/export": "deny",
    "import/no-namespace": "allow",
    "react/display-name": "deny",
    "react/exhaustive-deps": "deny",
    "react/jsx-key": "deny",
    "react/jsx-no-comment-textnodes": "deny",
    "react/jsx-no-duplicate-props": "deny",
    "react/jsx-no-target-blank": "deny",
    "react/jsx-no-undef": "deny",
    "react/no-children-prop": "deny",
    "react/no-danger-with-children": "deny",
    "react/no-direct-mutation-state": "deny",
    "react/no-find-dom-node": "deny",
    "react/no-is-mounted": "deny",
    "react/no-render-return-value": "deny",
    "react/no-string-refs": "deny",
    "react/no-unescaped-entities": "deny",
    "react/no-unknown-property": "deny",
    "react/require-render-return": "deny",
    "react/rules-of-hooks": "deny",
    "typescript/array-type": "allow",
    "typescript/no-duplicate-enum-values": "deny",
    "typescript/no-empty-object-type": "deny",
    "typescript/no-explicit-any": "deny",
    "typescript/no-extra-non-null-assertion": "deny",
    "typescript/no-misused-new": "deny",
    "typescript/no-non-null-asserted-optional-chain": "deny",
    "typescript/no-require-imports": "deny",
    "typescript/no-unnecessary-type-constraint": "deny",
    "typescript/no-unsafe-declaration-merging": "deny",
    "typescript/no-unsafe-function-type": "deny",
    "typescript/no-wrapper-object-types": "deny",
    "typescript/prefer-as-const": "deny",
    "typescript/prefer-namespace-keyword": "deny",
    "typescript/triple-slash-reference": "deny",
    "unicorn/catch-error-name": "deny",
    "unicorn/consistent-empty-array-spread": "deny",
    "unicorn/consistent-function-scoping": "deny",
    "unicorn/no-abusive-eslint-disable": "allow",
    "unicorn/no-hex-escape": "deny",
    "unicorn/no-invalid-fetch-options": "deny",
    "unicorn/no-magic-array-flat-depth": "deny",
    "unicorn/no-typeof-undefined": "deny",
    "unicorn/no-unnecessary-slice-end": "deny",
    "unicorn/no-useless-promise-resolve-reject": "deny",
    "unicorn/no-useless-spread": "deny",
    "unicorn/numeric-separators-style": "allow",
    "unicorn/prefer-array-flat-map": "deny",
    "unicorn/prefer-array-index-of": "deny",
    "unicorn/prefer-array-some": "deny",
    "unicorn/prefer-at": "deny",
    "unicorn/prefer-dom-node-append": "deny",
    "unicorn/prefer-native-coercion-functions": "allow",
    "unicorn/prefer-node-protocol": "deny",
    "unicorn/prefer-number-properties": "deny",
    "unicorn/prefer-optional-catch-binding": "deny",
    "unicorn/prefer-set-size": "deny",
    "unicorn/prefer-string-raw": "deny",
    "unicorn/prefer-string-replace-all": "deny",
    "unicorn/prefer-string-slice": "deny",
    "unicorn/prefer-structured-clone": "deny",
    "unicorn/prefer-top-level-await": "allow",
    "unicorn/text-encoding-identifier-case": "allow",
    camelcase: "error",
    "jsdoc-js/check-alignment": "error",
    "jsdoc-js/check-indentation": "error",
    "jsdoc-js/check-param-names": "error",
    "jsdoc-js/check-syntax": "error",
    "jsdoc-js/check-tag-names": ["error", { definedTags: ["remarks"] }],
    "jsdoc-js/require-description": "error",
    "jsdoc-js/require-jsdoc": [
      "error",
      {
        require: {
          FunctionDeclaration: true,
          MethodDefinition: true,
        },
      },
    ],
    "jsdoc-js/require-param": "error",
    "jsdoc-js/require-param-description": "error",
    "jsdoc-js/require-param-name": "error",
    "jsdoc-js/require-param-type": "off",
    "jsdoc-js/require-returns": "error",
    "jsdoc-js/require-returns-check": "error",
    "jsdoc-js/require-returns-description": "error",
    "jsdoc-js/require-returns-type": "off",
    "@effect/no-import-from-barrel-package": "error",
    "local/no-opaque-instance-fields": "error",
    "local-advanced/no-try-catch-in-effect-gen": "error",
    "local-advanced/no-type-assertions": "error",
    "local-advanced/require-return-yield-for-errors": "error",
    "local-advanced/no-effect-runsync-in-gen": "error",
    "local-advanced/prefer-effect-constructors": "error",
    "local-advanced/no-ambient-time": "error",
    "local-advanced/no-ambient-randomness": "error",
    "local-advanced/no-exported-mutable-bindings": "error",
    "local-advanced/no-effect-gen-in-routes": "error",
    "local-advanced/no-feature-layer-imports": "error",
    "local-advanced/no-db-imports-in-ui": "error",
    "typescript/unbound-method": "off",
  },
})
